#!/bin/bash -e

source $(dirname $(readlink -f ${0}))/tools.sh

HEAD=$(gittools_curbranch)
SINCE=$(gittools_really_match_curbranch)

if [ "$SINCE" == "" ]; then
	echo "ERROR: Could not find an upstream branch"
	exit 1
fi

gittools_check_work $SINCE $HEAD

for SHA in $(git log --reverse --format=format:%H  $HEAD ^$SINCE); do
	FNAME="$(git show --format=format:%f -s $SHA).patch"
	echo "Generating $FNAME"
	git diff $SHA~1 $SHA --no-prefix > $FNAME
done
