#!/bin/bash

source $(dirname $(readlink -f ${0}))/tools.sh

SINCE=$(gittools_really_match_curbranch)
unset DISPLAY
exec git format-patch -M $(gittools_get_patch_target_option) "$(gittools_prefix_opt)" --stdout "$@" $SINCE  | git imap-send
