#!/bin/bash

source $(dirname $(readlink -f ${0}))/tools.sh
HEAD=$(gittools_curbranch)

if [ "$1" != "" ]; then
	matching=$1
else
	matching=$(gittools_really_match_branch $HEAD)
fi
if [ "$matching" == "" ]; then
	echo "No matching integration branch for '$HEAD'"
	exit 1
fi

TAG=$(git describe --exact-match  --match checked/20[0-9]**/$HEAD 2> /dev/null)
if [ $? -eq 0 ]; then
	echo "Series already checked ($TAG)"
	exit 0
fi

echo "Checking patch from $matching to $HEAD"

(
	ERR=0
	COMMITS=$(git log --format=format:%H --reverse ^$matching HEAD)
	if [ $? -ne 0 ]; then
		exit 1
	fi
	for commit in $COMMITS; do
		echo "========== Checking commit $(git show --format=oneline -s ${commit}) ================"
		git cmd-check $commit || ERR=1
	done
	exit $ERR
)
RET=$?
if [ $RET -ne 0 ]; then
	echo "========== FAILED ================"
else
	echo "========== SUCCESS ================"
	git tag -m "Checked" checked/$(gittools_gen_timestamp)/$HEAD
fi
exit $RET
