#!/bin/bash
#
# Show commits which exist in a given range, but don't exist in the current
# branch and are marked for stable.
#

source $(dirname $(readlink -f ${0}))/tools.sh

if [ "$#" -ne 1 ]; then
        echo "Usage: stable show-missing-stable <commit range>"
        exit 1
fi

function stable_print {
	gittools_check_relevant $1
	if [ $? -ne 0 ]; then
		return
	fi
    echo $(git log -1 --oneline $1)
}

gittools_show_missing_iter $1 stable_print
