#!/bin/bash
#
# Show commits which exist in a given range, but don't exist in the current
# branch and are marked for stable.
#

source $(dirname $(readlink -f ${0}))/tools.sh

RANGE=''
if [ $# -gt 1 ]; then
        echo "Usage: stable show-missing [<commit range>]"
        exit 1
elif [  $# -eq 1 ]; then
	RANGE=$1
else
	RANGE="$(gittools_match_curstable)..origin/master"
fi

function stable_print {
	gittools_check_relevant $1
	if [ $? -ne 0 ]; then
		return
	fi
    echo $(git log -1 --oneline $1)
}

gittools_show_missing_iter $RANGE stable_print
